GET http://localhost:3000/users/1345/Jhon
?limit=10
&offset=20



PATCH http://localhost:3000/users
Content-Type: application/json
{
  "firtsName": "Johnas",
  "lastName": "Doe",
  "email": "jhon@doe.com",
  "password": "Password123$",
  "isAuth": true
}

DELETE http://localhost:3000/users

PUT http://localhost:3000/users
Content-Type: application/json
{
  "name": "John Doe"
}